### PR TITLE
Add snake case wrappers for current CamelCase

### LINKED ISSUE #46: Update the Function names to snake_case.
Hello, I've found this helpful but the problem is that, this library doesn't follow PEP-8, which recommends the usage of snake_case instead of camelCase or CaptialCase for function names, hope you fix it.

Thank you.

### PR DESCRIPTION
**Pull request by dennorske**
Will ensure backwards compatibility. Closes #46

### CODE REVIEW

**Comment by dennorske** [comment]
I've changed all functions and callbacks over to snake_case implementation. Could you advice how to change the callbacks correctly?
I guess we need to call both callbacks (both snake_case and CamelCase ones)
@habecker

**Comment by Cheaterman** [comment]
I would agree that you need to call both, but I kind of like that you did this! It'll look much more natural in Python!

**Comment by Cheaterman** [comment]
IMHO that could be the occasion to make the module names more meaningful : rename current (internal) `pysamp` module to `samp` (because it implements the SAMP API), create a new `pysamp` module with all the wrappers.

I suggest having internal callback handlers in `pysamp` that use the SAMP API, that would call some logic allowing handlers to be attached by users using decorators, something like
```python
from pysamp import on, show_player_dialog

@on.player_spawn
def ask_login(playerid):
    show_player_dialog(playerid, ...)  # Params missing of course
```

**Comment by dennorske** [comment]
I think this is stale, and that the whole interface needs to be redone. Closing

**Pull request closed without merging**
