### PR TITLE
sampctl release

### PR DESCRIPTION
**Pull request by S0P4**
- Release of the plugin as sampctl package.

The release form of the packet has to change

Slould be a `PySAMP-x.x.x.zip` containing a folder called `plugins` and inside the folder the .dll and .so of the last release.

### CODE REVIEW

**Comment by S0P4** [comment]
This is a file example of the release
[PySAMP-2.0.1.zip](https://github.com/pysamp/PySAMP/files/10459478/PySAMP-2.0.1.zip)

**Comment by dennorske** [comment]
Great initiative!!

**Comment by dennorske** [comment]
@Cheaterman we can do this yes? I'd be very interested in that 😎
We also need to release the pysamp api to pypi, and there's a few other things to do before that happens. Maybe we can do this at the same time 😜

**Comment by dennorske** [comment]
We will look into this once the 2.1 release is done. We are going to put things on PyPi and such.

**Pull request closed without merging**
