### PR TITLE
feat: reimplement callbacks and fix gmx and gamemode reloading

### LINKED ISSUE #31: Reload gamemode on gmx

### LINKED ISSUE #36: How to install and use pysamp?
Someone can help me to install and use "**PySAMP**"?

### LINKED ISSUE #37: Specific callbacks cause the server to crash
TypeError: OnPlayerInteriorChange() missing 3 required positional arguments: 'playerid', 'newinteriorid', and 'oldinteriorid'
TypeError: OnPlayerEnterCheckpoint() missing 1 required positional argument: 'playerid'

The last one is crashing the server

Many thanks to you for your help, and for developing PySAMP!

EDIT: I found out that the crash occurs when OnPlayerEnterDynamicCP is called from gamemode.amx, I didn't find a workaround, seems like a problem with the Python CallBacks

_Originally posted by @LivioMirandaJr in https://github.com/habecker/PySAMP/issues/36#issuecomment-753682732_

### PR DESCRIPTION
**Pull request by habecker**
- [X] reimplementation of callbacks
- [ ] document "pyreload" rcon command
- [x] document usage with docker
- [ ] document, that callbacks with return value "True" prevent other callbacks (filterscripts, gamemodes, plugins) from being called
- [x] do some more testing
- [x] add and document bat-script to auto install pysamp into a server

Closes #37, #36, #40

### CODE REVIEW

**Comment by dennorske** [comment]
@habecker good to go?

**Comment by habecker** [comment]
@dennorske Honestly, I don't know  .. it's been 3 months 😄. I'm testing it now

**Comment by habecker** [comment]
@dennorske It's almost done now, we only need documentation and more testing

**Comment by dennorske** [comment]
I'll have some time this weekend, and then I can work on the docker documentation.

**Review by dennorske — COMMENTED** [review]
# 3D Textlabels not defined (Fixed and tested)
image

Having an issue testing textlabels.

I added this to my samp.py:
(I guess this needs to be pushed as well, but i assume you have this wip) 
```py
def Create3DTextLabel(text, color, x, y, z, drawdistance, virtualworld, testLOS):
    return pysamp.Create3DTextLabel(text, color, x, y, z, drawdistance, virtualworld, testLOS)
 ```

-----
# Gamemode Reloading:
```py
from samp import *

def OnGameModeInit():
    print("OnGamemodeInit called")
    SetGameModeText('PySAMP')
    return True
    
def OnGameModeExit():
    print("OnGamemodeExit called")
    return True

def OnPyUnload():
    print("OnPyUnload called")
    OnGameModeExit()
    return True

def OnPyReload():
    print("OnPyReload called")
    OnGameModeInit()
    return True
    
def OnPlayerText(playerid, text):
    text = decode(text)
    if "restart" in text:
        SendRconCommand("gmx")

    return True
    
   ```
   
This prints `OnGamemodeInit called` in console when doing the reload, the other functions are not called. Expected?

**Review by dennorske — APPROVED** [review]

**Pull request merged**
